### ISSUE TITLE
Add user-friendly error screen when using wrong engine version

### ISSUE THREAD

**Issue by Germanunkol** [Germanunkol/trAInsported#80]

**Comment by jklmnn** [comment]
I tried to solve this and had some trouble because of the changing API between versions, but I got a piece of code that seems to work vor löve 0.8 and 0.9 (i don't think that someone is still using 0.7).  I just didn't got it integrated into the existing code.  
https://gist.github.com/jklmnn/95a9605c060a917f5859
love._version works at least since löve 0.8.0 and love.quit since 0.7.0. i tried it with 0.8.0 and 0.9.1.

**Comment by Germanunkol** [comment]
Hey, thanks for trying this out!

I'm busy with exams at the moment, but maybe I can get to integrating this in around a week or so.

**Comment by jklmnn** [comment]
I examined this further. It is possible to set `t.version = "0.9.1"` in the conf.lua file which gives a warning when the game is run with the wrong löve version. The problem is that the modules in main.lua are loaded before love.conf() is run. Therefore the error is occuring before the version is checked.

**Comment by jklmnn** [comment]
Tried to solve with #114
